name: CI/CD with FTP for HTML/CSS

on:
  push:
    branches:
      - main  # Workflow ini dijalankan pada push ke branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan job ini di runner Ubuntu

    steps:
      # Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install FTP client
      - name: Install FTP client
        run: sudo apt-get install lftp

      # Install Node.js dan npm
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '23.11.0'

      # make folder tes
      - name: make folder
        run: mkdir tes

      # Jalankan npm init (untuk menginisialisasi proyek Node.js)
      - name: Run npm init
        run: |
          npm init -y 

      # Deploy ke server menggunakan FTP
      - name: Deploy to FTP server
        run: |
          lftp -f "
          set ssl:verify-certificate no
          open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}:${{ secrets.FTP_PORT }}
          mirror -R ./ /. --ignore-time
          quit
          "
